<a href="https://colab.research.google.com/github/towardsai/tutorials/blob/master/neural_networks_tutorial_part_1/neural_networks_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Neural Networks from Scratch with Python Code and Math in Detail

* Tutorial: https://towardsai.net/p/machine-learning/building-neural-networks-from-scratch-with-python-code-and-math-in-detail-i-536fae5d7bbf 

* Github: https://github.com/towardsai/tutorials/tree/master/neural_networks_tutorial_part_1 



In [ ]:
# Import required libraries:
import numpy as np# Define input features:
input_features = np.array([[0,0],[0,1],[1,0],[1,1]])
print (input_features.shape)
print (input_features)# Define target output:
target_output = np.array([[0,1,1,1]])# Reshaping our target output into vector:
target_output = target_output.reshape(4,1)
print(target_output.shape)
print (target_output)# Define weights:
weights = np.array([[0.1],[0.2]])
print(weights.shape)
print (weights)# Bias weight:
bias = 0.3# Learning Rate:
lr = 0.05# Sigmoid function:
def sigmoid(x):
 return 1/(1+np.exp(-x))# Derivative of sigmoid function:
def sigmoid_der(x):
 return sigmoid(x)*(1-sigmoid(x))# Main logic for neural network:
 # Running our code 10000 times:for epoch in range(10000):
 inputs = input_features#Feedforward input:
 in_o = np.dot(inputs, weights) + bias #Feedforward output:
 out_o = sigmoid(in_o) #Backpropogation 
 #Calculating error
 error = out_o - target_output
 
 #Going with the formula:
 x = error.sum()
 print(x)
 
 #Calculating derivative:
 derror_douto = error
 douto_dino = sigmoid_der(out_o)
 
 #Multiplying individual derivatives:
 deriv = derror_douto * douto_dino #Multiplying with the 3rd individual derivative:
 #Finding the transpose of input_features:
 inputs = input_features.T
 deriv_final = np.dot(inputs,deriv)
 
 #Updating the weights values:
 weights -= lr * deriv_final #Updating the bias weight value:
 for i in deriv:
  bias -= lr * i #Check the final values for weight and biasprint (weights)
  
print (bias) #Taking inputs:
single_point = np.array([1,0]) #1st step:
result1 = np.dot(single_point, weights) + bias #2nd step:
result2 = sigmoid(result1) #Print final result
print(result2) #Taking inputs:
single_point = np.array([1,1]) #1st step:
result1 = np.dot(single_point, weights) + bias #2nd step:
result2 = sigmoid(result1) #Print final result
print(result2) #Taking inputs:
single_point = np.array([0,0]) #1st step:
result1 = np.dot(single_point, weights) + bias #2nd step:
result2 = sigmoid(result1) #Print final result
print(result2)

(4, 2)
[[0 0]
 [0 1]
 [1 0]
 [1 1]]
(4, 1)
[[0]
 [1]
 [1]
 [1]]
(2, 1)
[[0.1]
 [0.2]]
0.3
[0.59868766]
[0.64565631]
[0.57444252]


In [ ]:
# Import required libraries:
import numpy as np# Define input features:
input_features = np.array([[0,0],[0,1],[1,0],[1,1]])
print (input_features.shape)
print (input_features)# Define target output:
target_output = np.array([[0,1,1,1]])# Reshaping our target output into vector:
target_output = target_output.reshape(4,1)
print(target_output.shape)
print (target_output)# Define weights:
weights = np.array([[0.1],[0.2]])
print(weights.shape)
print (weights)# Define learning rate:
lr = 0.05# Sigmoid function:
def sigmoid(x):
 return 1/(1+np.exp(-x))# Derivative of sigmoid function:
def sigmoid_der(x):
 return sigmoid(x)*(1-sigmoid(x))# Main logic for neural network:
# Running our code 10000 times:for epoch in range(10000):
 inputs = input_features#Feedforward input:
 pred_in = np.dot(inputs, weights)#Feedforward output:
 pred_out = sigmoid(pred_in)#Backpropogation 
 #Calculating error
 error = pred_out - target_output
 x = error.sum()
 
 #Going with the formula:
 print(x)
 
 #Calculating derivative:
 dcost_dpred = error
 dpred_dz = sigmoid_der(pred_out)
 
 #Multiplying individual derivatives:
 z_delta = dcost_dpred * dpred_dz#Multiplying with the 3rd individual derivative:
 inputs = input_features.T
 weights -= lr * np.dot(inputs, z_delta)
 
 
#Taking inputs:
single_point = np.array([1,0])#1st step:
result1 = np.dot(single_point, weights)#2nd step:
result2 = sigmoid(result1)#Print final result
print(result2)#Taking inputs:
single_point = np.array([0,0])#1st step:
result1 = np.dot(single_point, weights)#2nd step:
result2 = sigmoid(result1)#Print final result
print(result2)#Taking inputs:
single_point = np.array([1,1])#1st step:
result1 = np.dot(single_point, weights)#2nd step:
result2 = sigmoid(result1)#Print final result
print(result2)

(4, 2)
[[0 0]
 [0 1]
 [1 0]
 [1 1]]
(4, 1)
[[0]
 [1]
 [1]
 [1]]
(2, 1)
[[0.1]
 [0.2]]
[0.52497919]
[0.5]
[0.57444252]


In [ ]:
# Import required libraries:
import numpy as np# Define input features:
input_features = np.array([[1,0,0,1],[1,0,0,0],[0,0,1,1],
 [0,1,0,0],[1,1,0,0],[0,0,1,1],
 [0,0,0,1],[0,0,1,0]])
print (input_features.shape)
print (input_features)# Define target output:
target_output = np.array([[1,1,0,0,1,1,0,0]])# Reshaping our target output into vector:
target_output = target_output.reshape(8,1)
print(target_output.shape)
print (target_output)# Define weights:
weights = np.array([[0.1],[0.2],[0.3],[0.4]])
print(weights.shape)
print (weights)# Bias weight:
bias = 0.3# Learning Rate:
lr = 0.05# Sigmoid function:
def sigmoid(x):
 return 1/(1+np.exp(-x))# Derivative of sigmoid function:
def sigmoid_der(x):
 return sigmoid(x)*(1-sigmoid(x))# Main logic for neural network:
# Running our code 10000 times:for epoch in range(10000):
 inputs = input_features#Feedforward input:
 pred_in = np.dot(inputs, weights) + bias#Feedforward output:
 pred_out = sigmoid(pred_in)#Backpropogation 
 #Calculating error
 error = pred_out - target_output
 
 #Going with the formula:
 x = error.sum()
 print(x)
 
 #Calculating derivative:
 dcost_dpred = error
 dpred_dz = sigmoid_der(pred_out)
 
 #Multiplying individual derivatives:
 z_delta = dcost_dpred * dpred_dz#Multiplying with the 3rd individual derivative:
 inputs = input_features.T
 weights -= lr * np.dot(inputs, z_delta)#Updating the bias weight value:
 for i in z_delta:
  bias -= lr * i#Printing final weights: 

print (weights)
print ("\n\n")
print (bias)#Taking inputs:
single_point = np.array([1,0,0,1])#1st step:
result1 = np.dot(single_point, weights) + bias#2nd step:
result2 = sigmoid(result1)#Print final result
print(result2)#Taking inputs:
single_point = np.array([0,0,1,0])#1st step:
result1 = np.dot(single_point, weights) + bias#2nd step:
result2 = sigmoid(result1)#Print final result
print(result2)#Taking inputs:
single_point = np.array([1,0,1,0])#1st step:
result1 = np.dot(single_point, weights) + bias#2nd step:
result2 = sigmoid(result1)#Print final result
print(result2)

(8, 4)
[[1 0 0 1]
 [1 0 0 0]
 [0 0 1 1]
 [0 1 0 0]
 [1 1 0 0]
 [0 0 1 1]
 [0 0 0 1]
 [0 0 1 0]]
(8, 1)
[[1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]]
(4, 1)
[[0.1]
 [0.2]
 [0.3]
 [0.4]]
[[0.1]
 [0.2]
 [0.3]
 [0.4]]



0.3
[0.68997448]
[0.64565631]
[0.66818777]
