# Random Number Generator Tutorial with Python

## Generating pseudorandom numbers with Python standard library

Python has a built-in module called random to generate a variety of pseudorandom numbers. Although it is recommended that this module should not be used for security purposes like cryptographic uses this will do for machine learning and data science. This module uses a PRNG called Mersenne Twister.

### Importing module: random

In [ ]:
import random

### Random numbers within a range

In [ ]:
#initialize the seed to 25
random.seed(25)

#generating random number between 10 and 20(both excluded)
print(random.randrange(10, 20))

#generating random number between 10 and 20(both included)
print(random.randint(10, 20))

16
10


### Random element from a sequence

In [ ]:
#initialize the seed to 2
random.seed(2)

#setting up the sequence
myseq = ['Towards', 'AI', 'is', 1]

#randomly choosing an element from the sequence
random.choice(myseq)

'Towards'

### Multiple random selections with different possibilities

In [ ]:
#initialize the seed to 25
random.seed(25)

#setting up the sequence
myseq = ['Towards', 'AI', 'is', 1]

#random selection of length 15
#10 time higher possibility of selecting 'Towards'
#5 time higher possibility of selecting 'AI'
#2 time higher possibility of selecting 'is'
#2 time higher possibility of selecting 1
random.choices(myseq, weights=[10, 5, 2, 2], k = 15)

['Towards',
 1,
 'is',
 'Towards',
 'is',
 'AI',
 'Towards',
 1,
 'Towards',
 'Towards',
 'Towards',
 'AI',
 'Towards',
 'AI',
 'is']

### Random element from a sequence without replacement

In [ ]:
#initialize the seed to 25
random.seed(25)

#setting up the sequence
myseq = ['Towards', 'AI', 'is', 1]

#randomly choosing an element from the sequence
random.sample(myseq, 2)

[1, 'Towards']

In [ ]:
#initialize the seed to 25
random.seed(25)

#setting up the sequence
myseq = ['Towards', 'AI', 'is', 1]

#randomly choosing an element from the sequence
#you are trying to choose 5 random elements from a sequence of lenth 4
#since the selection is without replacement it is not possible and hence the error
random.sample(myseq, 5)

ValueError: ignored

### Rearrange the sequence

In [ ]:
#initialize the seed to 25
random.seed(25)

#setting up the sequence
myseq = ['Towards', 'AI', 'is', 1]

#rearranging the order of elements of the list
random.shuffle(myseq)
myseq

['AI', 'is', 'Towards', 1]

### Floating-point random number

In [ ]:
#initialize the seed to 25
random.seed(25)

#random float number between 0 and 1 
random.random()

0.376962302390386

### Real-valued distributions

In [ ]:
#initialize the seed to 25
random.seed(25)

#random float number between 10 and 20 (both included)
print(random.uniform(10, 20))

#random float number mean 10 standard deviation 4
print(random.gauss(10, 4))

13.76962302390386
16.90247841037158


## Generating pseudorandom numbers with Numpy

In [ ]:
#importing random module from numpy
import numpy as np

### Uniform distributed floating values

In [ ]:
#initialize the seed to 25
np.random.seed(25)

#single uniformly distributed random number
np.random.rand()

0.8701241366272119

In [ ]:
#initialize the seed to 25
np.random.seed(25)

#uniformly distributed random numbers of length 10: 1-D array
np.random.rand(10)

array([0.87012414, 0.58227693, 0.27883894, 0.18591123, 0.41110013,
       0.11737555, 0.68496874, 0.43761106, 0.55622933, 0.36708032])

In [ ]:
#initialize the seed to 25
np.random.seed(25)

#uniformly distributed random numbers of 2 rows and 3 columns: 2-D array
np.random.rand(2, 3)

array([[0.87012414, 0.58227693, 0.27883894],
       [0.18591123, 0.41110013, 0.11737555]])

### Normal distributed floating values

In [ ]:
#initialize the seed to 25
np.random.seed(25)

#single normally distributed random number
np.random.randn()

0.22827308966608442

In [ ]:
#initialize the seed to 25
np.random.seed(25)

#normally distributed random numbers of length 10: 1-D array
np.random.randn(10)

array([ 0.22827309,  1.0268903 , -0.83958485, -0.59118152, -0.9568883 ,
       -0.22232569, -0.61991511,  1.83790458, -2.05323076,  0.86858305])

In [ ]:
#initialize the seed to 25
np.random.seed(25)

#normally distributed random numbers of 2 rows and 3 columns: 2-D array
np.random.randn(2, 3)

array([[ 0.22827309,  1.0268903 , -0.83958485],
       [-0.59118152, -0.9568883 , -0.22232569]])

###  Uniformly distributed integers in a given range

In [ ]:
#initialize the seed to 25
np.random.seed(25)

#single uniformly distributed random integer between 10 and 20
np.random.randint(10, 20)

14

In [ ]:
#initialize the seed to 25
np.random.seed(25)

#uniformly distributed random integer between 0 to 100 of length 10: 1-D array
np.random.randint(100, size=(10))

array([ 4, 62, 90, 15, 61, 23, 44, 50,  8, 28])

In [ ]:
#initialize the seed to 25
np.random.seed(25)

#uniformly distributed random integer between 0 to 100 of 2 rows and 3 columns: 2-D array
np.random.randint(100, size=(2, 3))

array([[ 4, 62, 90],
       [15, 61, 23]])

### Random elements from a defined list

In [ ]:
#initialize the seed to 25
random.seed(25)

#setting up the sequence
myseq = ['Towards', 'AI', 'is', 1]

#randomly choosing an element from the sequence
np.random.choice(myseq)

'Towards'

In [ ]:
#initialize the seed to 25
random.seed(25)

#setting up the sequence
myseq = ['Towards', 'AI', 'is', 1]

#randomly choosing elements from the sequence: 2-D array
np.random.choice(myseq, size=(2, 3))

array([['is', 'AI', 'Towards'],
       ['Towards', 'Towards', 'AI']], dtype='<U7')

In [ ]:
#initialize the seed to 25
random.seed(25)

#setting up the sequence
myseq = ['Towards', 'AI', 'is', 1]

#randomly choosing elements from the sequence with defined probabilities
#The probability for the value to be 'Towards' is set to be 0.1
#The probability for the value to be 'AI' is set to be 0.6
#The probability for the value to be 'is' is set to be 0.05
#The probability for the value to be 1 is set to be 0.25
#0.1 + 0.6 + 0.05 + 0.25 = 1
np.random.choice(myseq, p=[0.1, 0.6, 0.05, 0.25], size=(2, 3))

array([['AI', 'AI', '1'],
       ['1', 'Towards', 'AI']], dtype='<U7')

### Binomial distributed values

In [ ]:
#initialize the seed to 25
np.random.seed(25)

#10 number of trials with probability of 0.5 each
np.random.binomial(n=10, p=0.5, size=10)

array([7, 5, 4, 4, 5, 3, 6, 5, 5, 4])

### Poisson Distribution values

In [ ]:
#initialize the seed to 25
np.random.seed(25)

#rate 2 and size 10
np.random.poisson(lam=2, size=10)

array([3, 1, 3, 1, 2, 2, 3, 3, 0, 2])

### Chi Square distribution

In [ ]:
#initialize the seed to 25
np.random.seed(25)

#degree of freedom 2 and size (2, 3)
np.random.chisquare(df=2, size=(2, 3))

array([[4.08235236, 1.74587315, 0.65378557],
       [0.41137173, 1.05899821, 0.24971095]])

<center><h1>Thank you</h1></center>